CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );
--
-- CREATE TABLE IF NOT EXISTS items ( id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, user_id BIGINT, url VARCHAR(1000), CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id), UNIQUE(id, url) );
-- На данный момент вам достаточно создать таблицы для двух сущностей, которые вы уже разработали — Item и User.
-- CREATE TABLE IF NOT EXISTS tags ( id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, item_id BIGINT, name VARCHAR(50), CONSTRAINT fk_tags_to_items FOREIGN KEY(item_id) REFERENCES items(id) );